### ISSUE TITLE
full dataset available?

### ISSUE THREAD

**Issue by julienmmm** [jbelien/elections-be-api#8]
Hello,

I am very interested by your public api and I've beginning to play with it. 
However, the data do not seem to be complete, do you know if you plan to provide the full results data set?

Thanks for your help!

Julien

**Comment by jbelien** [comment]
Hello @julienmmm ,

You can use the API with the full dataset here : https://api.elections.openknowledge.be/v1/
Or you can download the full dataset here : https://2019.elections.openknowledge.be/

**Comment by julienmmm** [comment]
Hello Jerom,

Thanks for  the urls!

Regarding the api, I've try to call it with base url https://api.elections.openknowledge.be/v1/ / https://api.elections.openknowledge.be/new but it is not working, the only api url working for me is https://api.elections.openknowledge.be/.
By example if I want to get the results for the chamber, by canton I get "https://api.elections.openknowledge.be/format-r/results/2019/CK/K" and it works but does not return complete data.
If I try the same url with new/v1 : "https://api.elections.openknowledge.be/v1/format-r/results/2019/CK/K", I get an error "Cannot GET https://api.elections.openknowledge.be/format-r/results/2019/CK/K".
Could you help me with that?

**Comment by jbelien** [comment]
The first API https://api.elections.openknowledge.be/ was build in a few days.
I decided then to rebuild it properly. The new API is indeed https://api.elections.openknowledge.be/v1/ and is synced with this repo.
I suggest you have a look at the new routes : https://github.com/jbelien/elections-be-api/blob/master/config/routes.php

For instance, the results for the Chambre/Kamer by Canton are now available here : https://api.elections.openknowledge.be/v1/format-r/result/2019/CK/K

**Comment by julienmmm** [comment]
result instead of result**s**, ... ;-)

Thanks for your help Jonathan!
