### ISSUE TITLE
elections results at the "M : Bureau principal de commune / Gemeentehoofdbureau" level available

### ISSUE THREAD

**Issue by julienmmm** [jbelien/elections-be-api#9]
Hello,

It seems that the elections results (for the chamber in my case) is not available at the M level (M : Bureau principal de commune / Gemeentehoofdbureau), only at K level.

While the query https://api.elections.openknowledge.be/v1/format-r/result/2019/CK/K returns tons of data, this one does not return anything: https://api.elections.openknowledge.be/v1/format-r/result/2019/CK/M.

Is my query badly formatted or the data at this detail level are not available from the api?

**Comment by jbelien** [comment]
It's indeed not available.
I think `M` level will only be available for municipal elections.
